### PR TITLE
Update venn.m

### PR DESCRIPTION
**Pull request by farid-zare**
- Resolve problem with colors for Venn diagrams of 2 and 3
- Add optional font size input

### CODE REVIEW

**Review by manhowong — APPROVED** [review]
Hi farid-zare, thanks so much for the fixes. I have reviewed your changes. Everything looks great, except for the label color option (`labelC`) that got commented out probably by mistake (Line 236).
Thanks again for your contribution!

**Comment by farid-zare** [comment]
Thanks for your reply. Great!

**Comment by farid-zare** [comment]
Dear Man,
I am also a developer in the COBRA Toolbox, see here:
https://github.com/opencobra/cobratoolbox
It would be great to add your repository as a submodule to the COBRA Toolbox so it would be always updated. However as the COBRA toolbox currently has a function name 'venn', we have to change your function name to avoid conflicts.
Please let me know if you are interested to do that.

**Comment by manhowong** [comment]
Hey Farid, I am happy to contribute to the COBRA Toolbox. Feel free to add this repo as a submodule and change the function name.

**Pull request merged**
